### ISSUE TITLE
Debugging errors

### ISSUE THREAD

**Issue by snwfdhmp** [elastos/Elastos.ELA.SPV#67]
### You should not panic(err)

https://github.com/elastos/Elastos.ELA.SPV/blob/96a6ad10e258a89e51e285f123bd33a554eb92da/wallet/store/sqlite/addrs.go#L104-L106

Hey dude,

Just a friendly advice. You should not panic(err). You’d rather use [a package like this](https://github.com/snwfdhmp/errlog) for debugging your errors. Debug your code with :

1. Clear stack trace
2. Failing func call highlighting

<img width="999" alt="example" src="https://user-images.githubusercontent.com/23099246/53098953-11310c80-3525-11e9-8f6f-302791743cdf.png">

It’s way more easier then to debug.

Real better than panic-ing (in most case). You can still force exit if you need it.

I would be happy to get your feedbacks.

**Comment by alexpan0610** [comment]
Hi @snwfdhmp, thanks for your friendly advice, I'll explain why there is the panic.

The AddrsBatch() method is designed never return any error, or all batch methods of  database are designed never return errors.  Because a batch failure only happens in two situations, first is hardware malfunction, second is a previous batch not committed somewhere.

In first situation, we can't recover the error by some magic code, so we panic.
In second situation, the error its self is useless, we panic it to tell there are wrong codes somewhere else.

It's happy to have your interest to our project.
